spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5452/test
    username: user
    password: password
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30s
      max-create-connection-time: 30s
      max-acquire-time: 30s
      max-life-time: 30s
      validation-query: SELECT 1
  liquibase:
    url: jdbc:postgresql://localhost:5452/test
    user: user
    password: password
    change-log: classpath:/db/master.xml
    enabled: true
server:
  port: 7999

logging:
  level:
    root: info